add validator TRX addresses (TRC20)
python-validators/validators pull request #277
Opened 2023-06-11 08:07 UTC by msamsami

This is a validator for TRC20 Tron (TRX) addresses.

2023-06-12 08:05 UTC, joe733 commented
Hi @msamsami thanks for the PR.

Can you move both #276 & #277 to a folder `crypto_addresses` under `validators`, like so?

```c
.
|---- validators
    |---- crypto_addresses
        |---- eth_address.py
        |---- trx_address.py
```

And do the same with their corresponding tests?

2023-06-12 08:10 UTC, msamsami commented
Hi @joe733 

Sure. I'll move `btc_address.py` and its test to the new directories as well.

2023-06-12 10:28 UTC, msamsami commented
> Hi @msamsami thanks for the PR.
> 
> Can you move both #276 & #277 to a folder `crypto_addresses` under `validators`, like so?
> 
> ```c
> .
> |---- validators
>     |---- crypto_addresses
>         |---- eth_address.py
>         |---- trx_address.py
> ```
> 
> And do the same with their corresponding tests?

Hi @joe733 

It's done. Please merge #276 and then #277 to avoid any conflicts. The final structure would be like this:

```c
.
|---- tests
    |---- crypto_addresses
        |---- __init__.py
        |---- test_btc_address.py
        |---- test_eth_address.py
        |---- test_trx_address.py

|---- validators
    |---- crypto_addresses
        |---- __init__.py
        |---- btc_address.py
        |---- eth_address.py
        |---- trx_address.py

```

2023-06-17 17:00 UTC, joe733 requested changes
Shouldn't PR #277 be tracking TRX addresses?

2023-06-26 08:41 UTC, msamsami commented on poetry.lock
> +name = "pysha3"
I will restructure this PR after #276 is accepted.

2023-06-29 04:35 UTC, joe733 commented
@msamsami please sync `add-trx-validator` branch from upstream.

2024-04-04 02:19 UTC, yozachar commented
Ref: https://github.com/python-validators/validators/pull/278#issuecomment-2036013050

2024-04-04 02:19 UTC, closed without merging