feat: add validator for trx addresses
python-validators/validators pull request #384
Opened 2024-07-02 08:22 UTC by msamsami

* A new validator is added for the Tron (TRC20) address

2024-07-03 12:31 UTC, yozachar requested changes

2024-07-03 12:31 UTC, yozachar commented on CHANGES.md
> +
Please add a separator after line `27` and after line `43` (like on [line 120](https://github.com/python-validators/validators/pull/384/files#diff-d975bf659606195d2165918f93e1cf680ef68ea3c9cab994f033705fea8238b2R120
)), to group `patch`ed changes together.

```diff
**Full ...

+---

# 0. ...
```

2024-07-04 02:33 UTC, yozachar approved these changes
LGTM!

2024-07-04 02:33 UTC, merged

2024-07-04 03:45 UTC, yozachar commented
@msamsami, there's is something odd about the `Table of Contents` in the `crypto_address` documentation see: https://yozachar.github.io/pyvalidators/stable/api/crypto_addresses/, any idea why?

2024-07-04 07:30 UTC, msamsami commented
> @msamsami, there's is something odd about the `Table of Contents` in the `crypto_address` documentation see: https://yozachar.github.io/pyvalidators/stable/api/crypto_addresses/, any idea why?

The table of contents in the right sidebar? I noticed it just now. I ran the `python package/export TYPE` commands once again. No changes to the files! And it's the same on local—no idea why!