feat: add whitespace filtering to iban validator
python-validators/validators pull request #391
Opened 2024-07-19 08:40 UTC by Erawpalassalg

- add a new function to filter whitespace to IBAN validator

2024-07-19 09:00 UTC, yozachar commented
Hi, @Erawpalassalg, this library does not perform input data sanitation (mostly). See the [cards module](https://github.com/python-validators/validators/blob/2dc2a9e5412c92fd7f306d0b45171beb9e87a1e7/src/validators/card.py). Those numbers could be separated by spaces, hyphens, or slashes, but that's not taken into account for validation.

2024-07-19 09:17 UTC, Erawpalassalg commented
Hi @yozachar, thanks for letting me know.

Would this matter be open to discussion? As I believe that by only validating the machine-readable format this lib puts the formatting pressure on the end user rather than on the developer/company storing the numbers.

Could this at least be stated very clearly in the docs? (For the IBAN case, the discrepancy between the human-readable format and the machine-readable format is a whole part of the [Wikipedia](https://en.wikipedia.org/wiki/International_Bank_Account_Number) related page)

2024-07-19 12:26 UTC, yozachar commented
> Would this matter be open to discussion? As I believe that by only validating the machine-readable format this lib puts the formatting pressure on the end user rather than on the developer/company storing the numbers.

I suppose an end-user would be a non-developer, in that case, they are never going to use this library directly. Another developer/company who works for the end-user/client, making use of this library, can and should, sanitize the human-readable input (from the end-user) before validating it.

Regardless, if spaces are the only separators, I suppose it can be considered (even though input sanitization is beyond the scope of this library).

2024-07-19 12:33 UTC, yozachar requested changes

2024-07-19 12:33 UTC, yozachar commented on src/validators/iban.py
> +    filtered_value = _filter_whitespace(value)
```diff
- filtered_value = _filter_whitespace(value)
+ if not value:
+     return False
+ 
+ # Remove Unicode white-spaces from the string.
+ value = "".join(filter(lambda x: not x.isspace(), value))
```

I think the function call can be skipped.

2024-07-19 15:09 UTC, Erawpalassalg commented
I went a little further with this IBAN stuff.

Apparently a lib already does all the validation stuff, taking into account the specifics of the ISO-13616 mentioned in [this document](["IBAN REGISTRY – This registry provides detailed information about all ISO 13616-compliant national IBAN formats. – Release 97 – March 2024"](https://www.swift.com/resource/iban-registry-pdf)), and it's called [schwifty](https://github.com/mdomke/schwifty).

The interesting stuff when testing with this lib are:
- They don't care about spaces in the input (suppressing them internally)
- Some of their invalid test cases actually pass validators' validation process, said test cases are:
  - GB96 BARC 2020 1530 0934 591 -- Too long
  - GB12 BARC 2020 1530 093A 59 -- Wrong account format (country specific)
  - GB01 BARC 2071 4583 6083 87 -- Wrong checksum digits
  - GB00 HLFX 1101 6111 4553 65 -- Wrong checksum digits

So, I was wondering if it would be interesting to start using schwifty as a dependency to be compliant with ISO-13616?

2024-07-20 04:27 UTC, yozachar commented
Cool, I'm open to adding it as an optional dependency.

2025-03-29 04:37 UTC, yozachar commented
Are you working on this?

2025-04-26 16:14 UTC, closed without merging